apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-planner"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/component: planner
spec:
  replicas: {{ .Values.planner.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: planner
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: planner
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - name: planner
          image: "{{ .Values.planner.repository.image }}:{{ .Values.appVersion | default .Chart.Version }}"
          ports:
            - name: web
              containerPort: 80
          {{- if .Values.planner.local.enabled }}
          volumeMounts:
            - mountPath: /usr/share/nginx/html/index.html
              name: index-dev
              subPath: index.html
          {{- end }}
          resources:
            requests:
              memory: 32Mi
              cpu: 10m
            limits:
              memory: 32Mi
      {{- if .Values.planner.local.enabled }}
      volumes:
        - name: index-dev
          configMap:
            name: {{.Release.Name }}-planner-index-dev
      {{- end }}