hostname: passage.localhost
mariadb:
  auth:
    rootPassword: root-password
    password: password
  persistence:
    enabled: false
planner:
  replicaCount: 1
  repository:
    image: k3d-registry.localhost:5111/ijmacd/passage-planner
  ingress:
    tls:
      enabled: true
  local:
    enabled: true
logbook:
  replicaCount: 1
  repository:
    image: k3d-registry.localhost:5111/ijmacd/logbook
  ingress:
    class: traefik
    tls:
      enabled: true
  local:
    enabled: true
  auth:
    password: password
websockify:
  ingress:
    tls:
      enabled: true
