hostname: passage.ijmacd.com
mariadb:
  auth:
    database: passage
    username: passage_user
  initdbScriptsConfigMap: logbook-mariadb-init
  primary:
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 200m
planner:
  replicaCount: 1
  repository:
    image: ijmacd/passage-planner
  ingress:
    path: "/"
    tls:
      enabled: false
  local:
    enabled: false
logbook:
  replicaCount: 1
  repository:
    image: ijmacd/logbook
  ingress:
    path: "/logbook"
    tls:
      enabled: false
  local:
    enabled: false
websockify:
  enabled: true
  replicaCount: 1
  repository:
    image: efrecon/websockify
  ingress:
    path: "/wsais"
    tls:
      enabled: false
nmeaRepeater:
  enabled: true
  repository:
    image: ijmacd/nmea-repeater
    tag: 1.0.0
