{{ if .Values.websockify.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ .Release.Name }}-websockify'
spec:
  rules:
  - host: '{{ .Values.hostname }}'
    http:
      paths:
      - path: '{{ .Values.websockify.ingress.path }}'
        pathType: Prefix
        backend:
          service:
            name: '{{ .Release.Name }}-websockify'
            port:
              name: ws
  {{- if .Values.websockify.ingress.tls.enabled }}
  tls:
  - hosts:
    - '{{ .Values.hostname }}'
    secretName: {{ .Release.Name }}-cert
  {{- end }}
{{ end }}