apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-logbook"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/component: logbook
spec:
  replicas: {{ .Values.logbook.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: logbook
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/component: logbook
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - name: logbook
          image: '{{ .Values.logbook.repository.image }}:{{ .Values.appVersion | default .Chart.Version }}'
          env:
            - name: BASE_URL
              value: {{ .Values.logbook.ingress.path }}
            - name: DATABASE_DSN
              value: mysql:host={{ .Release.Name }}-mariadb;dbname={{ .Values.mariadb.auth.database }}
            - name: DATABASE_USER
              value: {{ .Values.mariadb.auth.username }}
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb
                  key: mariadb-password
            - name: API_AUTH_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-logbook
                  key: auth-pass
          ports:
            - name: web
              containerPort: 80
          {{- if .Values.logbook.local.enabled }}
          volumeMounts:
            - mountPath: /var/www/html
              name: src
          {{- end }}
          resources:
            requests:
              memory: 48Mi
              cpu: 10m
            limits:
              memory: 64Mi
      {{- if .Values.logbook.local.enabled }}
      volumes:
        - name: src
          hostPath:
            path: /ijmacd/passage/logbook/src
      {{- end }}

