apiVersion: v1
kind: ConfigMap
metadata:
  name: logbook-mariadb-init
data:
  {{- $files := .Files }}
  {{- range tuple "data/create.sql" }}
  {{ base . }}: |
{{ $files.Get . | indent 4 }}
  {{- end }}