{{ if eq .Values.logbook.ingress.class "traefik" }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-path-prefix
  namespace: "{{ .Release.Namespace }}"
spec:
  stripPrefix:
    prefixes:
      - "{{ .Values.logbook.ingress.path }}"
    forceSlash: true
{{ end }}
