apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ .Release.Name }}-logbook'
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: '{{ .Values.hostname }}'
    http:
      paths:
      - path: '{{ .Values.logbook.ingress.path }}(/|$)(.*)'
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Release.Name }}-logbook'
            port:
              name: web
  {{- if .Values.logbook.ingress.tls.enabled }}
  tls:
  - hosts:
    - '{{ .Values.hostname }}'
    secretName: {{ .Release.Name }}-cert
  {{- end }}