{{ if .Values.logbook.local.enabled }}
apiVersion: traefik.containo.us/v1alpha1
{{ else }}
apiVersion: traefik.io/v1alpha1
{{ end}}
kind: Middleware
metadata:
  name: strip-path-prefix
  namespace: "{{ .Release.Namespace }}"
spec:
  stripPrefix:
    prefixes:
      - "{{ .Values.logbook.ingress.path }}"
    forceSlash: true
