apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-nmea-repeater
  namespace: {{ .Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: nmea-repeater
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: nmea-repeater
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: nmea-repeater
    spec:
      containers:
        - name: nmea-repeater
          image: docker.io/ijmacd/nmea-repeater:1.0.0
          ports:
            - name: nmea-tcp
              containerPort: 10110
              protocol: TCP
            - name: nmea-udp
              containerPort: 10110
              protocol: UDP