{{ if .Values.websockify.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-websockify"
  labels:
    app.kubernetes.io/name: websockify
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  selector:
    app.kubernetes.io/name: websockify
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  ports:
    - protocol: TCP
      name: ws
      port: 80
      targetPort: ws
{{ end }}